//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RehberArama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchModels
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Unite { get; set; }
        public string Fabrika { get; set; }
        public string Pozisyon { get; set; }
        public string Is_Tel1 { get; set; }
        public string Is_Tel2 { get; set; }
        public string Kurumsal_Tel { get; set; }
        public string Telsiz_No { get; set; }
        public string Email { get; set; }
        public string resimUrl { get; set; }
    }
}
